"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.recordMapping = void 0;
exports.recordMapping = {
    //CRM -> Catalyst
    charge: {
        chargeName: "Name",
        charge: "Charge_Product.id",
        customerReferenceName: "Customer_Reference_Name",
        quantity: "Quantity",
        listPrice: "Amount",
        discount: "Discount",
        project: "Opportunity.id",
        delivery: "Delivery.id",
        territory: "Territory.id",
        billingOffice: "Billing_Office.id",
        territoryPrice: "Internal_Rate",
        vendorPrice: "Purchase_Price",
        invoiceAgreement: "Invoice_Agreement",
        totalExVat: "Total",
        invoiceDate: "Invoice_Date",
        invoiceIDBilling: "Billing_Office_Invoice.id",
        invoiceIDTerritory: "Territory_Invoice.id",
        invoiceIDDelivery: "Delivery_Invoice.id",
        customer: "Organisation.id",
        invoiceVia: "Invoice_Via.id",
        CRMID: "id",
        ITQ_PO: "ITQ_PO",
        description: "Description",
        status: "Status",
        startPeriod: "Start_Period",
        endPeriod: "End_Period",
        sku: "SKU",
        Billing_Office_Processed_ID: "Billing_Office_Processed_ID",
        Territory_Office_Processed_ID: "Territory_Office_Processed_ID",
        Delivery_Office_Processed_ID: "Delivery_Office_Processed_ID",
    },
    //CRM -> Catalyst
    service: {
        billingInvoiceTill: "Billing_Office_Invoiced_Till",
        territoryInvoiceTill: "Territory_Invoiced_Till",
        deliveryInvoiceTill: "Delivery_Invoiced_Till",
        startDate: "Contract_Start_Date",
        endDate: "Contract_End_Date",
        project: "Opportunity.id",
        product: "Service_Product.id",
        billingOffice: "Billing_Office.id",
        delivery: "Delivery.id",
        territory: "Territory.id",
        billingPeriod: "Billing_Period",
        quantity: "Quantity",
        listPrice: "Amount",
        vendorPrice: "Purchase_Price",
        territoryPrice: "Internal_Rate",
        discount: "Discount",
        totalExVat: "Total",
        description: "Name",
        customer: "Organisation.id",
        invoiceVia: "Invoice_Via.id",
        CRMID: "id",
        agreedUntil: "Agreed_Until",
    },
    //CRM -> Catalyst
    mutation: {
        billingOfficeInvoice: "Billing_Office_Invoice.id",
        billingOfficeInvoiceAmount: "Billing_Office_Invoice_Amount",
        billingOfficeInvoicing: "Billing_Office_Invoicing",
        deliveryInvoice: "Delivery_Invoice.id",
        deliveryInvoiceAmount: "Delivery_Invoice_Amount",
        deliveryInvoicing: "Delivery_Invoicing",
        territoryInvoice: "Territory_Invoice.id",
        territoryInvoiceAmount: "Territory_Invoice_Amount",
        territoryInvoicing: "Territory_Invoicing",
        effectiveFrom: "Effective_from",
        effectiveToBillingOffice: "Effective_to_Billing_Office",
        effectiveToDelivery: "Effective_to_Delivery",
        effectiveToTerritory: "Effective_to_Territory",
        processedOn: "Processed_on",
        name: "Name",
        status: "Status",
        service: "Service.id",
        newAmount: "New_Amount",
        newDiscount: "New_Discount",
        newInternalRate: "New_Internal_Rate",
        newPurchasePrice: "New_Purchase_Price",
        newQuantity: "New_Quantity",
        previousAmount: "Previous_Amount",
        previousDiscount: "Previous_Discount",
        previousInternalRate: "Previous_Internal_Rate",
        previousPurchasePrice: "Previous_Purchase_Price",
        previousQuantity: "Previous_Quantity",
        CRMID: "id",
    },
};
