/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Curtains: typeof import('./src/components/icons/curtains.vue')['default']
    Floor: typeof import('./src/components/icons/floor.vue')['default']
    Gamma: typeof import('./src/components/icons/gamma.vue')['default']
    Karwei: typeof import('./src/components/icons/karwei.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Window: typeof import('./src/components/icons/window.vue')['default']
  }
}
